// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: datamigrate.sql

package queries

import (
	"context"
)

const getGooseMaxAppliedVersion = `-- name: GetGooseMaxAppliedVersion :one
SELECT CAST(COALESCE(MAX(version_id), 0) AS INTEGER) AS max_version FROM goose_db_version WHERE is_applied = 1
`

func (q *Queries) GetGooseMaxAppliedVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGooseMaxAppliedVersion)
	var max_version int64
	err := row.Scan(&max_version)
	return max_version, err
}

const listDatamigrateAppliedNames = `-- name: ListDatamigrateAppliedNames :many
SELECT name FROM tbl_datamigrate_applied ORDER BY name
`

func (q *Queries) ListDatamigrateAppliedNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDatamigrateAppliedNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGooseAppliedVersionIDs = `-- name: ListGooseAppliedVersionIDs :many
SELECT version_id FROM goose_db_version WHERE is_applied = 1 ORDER BY version_id
`

func (q *Queries) ListGooseAppliedVersionIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listGooseAppliedVersionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var version_id int64
		if err := rows.Scan(&version_id); err != nil {
			return nil, err
		}
		items = append(items, version_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDatamigrateApplied = `-- name: UpsertDatamigrateApplied :exec
INSERT INTO tbl_datamigrate_applied (name, applied_at)
VALUES (?, datetime('now'))
ON CONFLICT(name) DO NOTHING
`

func (q *Queries) UpsertDatamigrateApplied(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, upsertDatamigrateApplied, name)
	return err
}
