// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: external_api_logs.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createExternalAPILog = `-- name: CreateExternalAPILog :one
INSERT INTO tbl_external_api_logs (
	checkout_id,
	service,
	api,
	endpoint,
	http_method,
	payload,
	response,
	status_code,
	error_message,
	is_successful,
	created_at,
	updated_at
) VALUES (
	?, ?, ?, ?, ?,
	?, ?, ?, ?, ?,
	?, ?
) RETURNING id, checkout_id, service, api, endpoint, http_method, payload, response, status_code, error_message, is_successful, created_at, updated_at
`

type CreateExternalAPILogParams struct {
	CheckoutID   sql.NullInt64
	Service      string
	Api          string
	Endpoint     string
	HttpMethod   string
	Payload      sql.NullString
	Response     sql.NullString
	StatusCode   sql.NullInt64
	ErrorMessage sql.NullString
	IsSuccessful int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateExternalAPILog(ctx context.Context, arg CreateExternalAPILogParams) (TblExternalApiLog, error) {
	row := q.db.QueryRowContext(ctx, createExternalAPILog,
		arg.CheckoutID,
		arg.Service,
		arg.Api,
		arg.Endpoint,
		arg.HttpMethod,
		arg.Payload,
		arg.Response,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.IsSuccessful,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TblExternalApiLog
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.Service,
		&i.Api,
		&i.Endpoint,
		&i.HttpMethod,
		&i.Payload,
		&i.Response,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.IsSuccessful,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
