// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: link_click.sql

package queries

import (
	"context"
	"database/sql"
)

const countLinkClicksByLinkID = `-- name: CountLinkClicksByLinkID :one
SELECT COUNT(*) as count
FROM tbl_link_clicks
WHERE link_id = ?
`

func (q *Queries) CountLinkClicksByLinkID(ctx context.Context, linkID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinkClicksByLinkID, linkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkClick = `-- name: CreateLinkClick :exec
INSERT INTO tbl_link_clicks (
    link_id,
    clicked_at,
    referrer,
    user_agent,
    ip_hash,
    device,
    utm_source,
    utm_medium,
    utm_campaign
) VALUES (
    ?,
    datetime('now'),
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateLinkClickParams struct {
	LinkID      string
	Referrer    sql.NullString
	UserAgent   sql.NullString
	IpHash      sql.NullString
	Device      sql.NullString
	UtmSource   sql.NullString
	UtmMedium   sql.NullString
	UtmCampaign sql.NullString
}

func (q *Queries) CreateLinkClick(ctx context.Context, arg CreateLinkClickParams) error {
	_, err := q.db.ExecContext(ctx, createLinkClick,
		arg.LinkID,
		arg.Referrer,
		arg.UserAgent,
		arg.IpHash,
		arg.Device,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
	)
	return err
}

const getLinkClicksByLinkID = `-- name: GetLinkClicksByLinkID :many
SELECT
    id,
    link_id,
    clicked_at,
    referrer,
    user_agent,
    ip_hash,
    device,
    utm_source,
    utm_medium,
    utm_campaign
FROM tbl_link_clicks
WHERE link_id = ?
ORDER BY clicked_at DESC
`

func (q *Queries) GetLinkClicksByLinkID(ctx context.Context, linkID string) ([]TblLinkClick, error) {
	rows, err := q.db.QueryContext(ctx, getLinkClicksByLinkID, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TblLinkClick
	for rows.Next() {
		var i TblLinkClick
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ClickedAt,
			&i.Referrer,
			&i.UserAgent,
			&i.IpHash,
			&i.Device,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
