// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: memo_recipient.sql

package queries

import (
	"context"
	"database/sql"
)

const createMemoRecipient = `-- name: CreateMemoRecipient :one
INSERT INTO tbl_memo_recipients (memo_id, staff_id, created_at)
VALUES (?, ?, datetime('now'))
RETURNING id
`

type CreateMemoRecipientParams struct {
	MemoID  int64
	StaffID int64
}

func (q *Queries) CreateMemoRecipient(ctx context.Context, arg CreateMemoRecipientParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMemoRecipient, arg.MemoID, arg.StaffID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteMemoRecipientsByMemoID = `-- name: DeleteMemoRecipientsByMemoID :exec
DELETE FROM tbl_memo_recipients
WHERE memo_id = ?
`

func (q *Queries) DeleteMemoRecipientsByMemoID(ctx context.Context, memoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMemoRecipientsByMemoID, memoID)
	return err
}

const getMemoRecipientStaffIDs = `-- name: GetMemoRecipientStaffIDs :many
SELECT staff_id
FROM tbl_memo_recipients
WHERE memo_id = ?
`

func (q *Queries) GetMemoRecipientStaffIDs(ctx context.Context, memoID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getMemoRecipientStaffIDs, memoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var staff_id int64
		if err := rows.Scan(&staff_id); err != nil {
			return nil, err
		}
		items = append(items, staff_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoRecipientsWithActions = `-- name: GetMemoRecipientsWithActions :many
SELECT
    r.staff_id,
    s.first_name,
    s.middle_name,
    s.last_name,
    a.status AS action_status,
    a.reject_reason,
    a.accepted_at,
    a.rejected_at,
    a.created_at AS action_created_at
FROM tbl_memo_recipients r
JOIN tbl_staffs s ON s.id = r.staff_id
LEFT JOIN tbl_memo_staff_actions a ON a.memo_id = r.memo_id AND a.staff_id = r.staff_id
WHERE r.memo_id = ?
ORDER BY s.last_name ASC, s.first_name ASC
`

type GetMemoRecipientsWithActionsRow struct {
	StaffID         int64
	FirstName       string
	MiddleName      sql.NullString
	LastName        string
	ActionStatus    sql.NullString
	RejectReason    sql.NullString
	AcceptedAt      sql.NullString
	RejectedAt      sql.NullString
	ActionCreatedAt sql.NullString
}

func (q *Queries) GetMemoRecipientsWithActions(ctx context.Context, memoID int64) ([]GetMemoRecipientsWithActionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMemoRecipientsWithActions, memoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemoRecipientsWithActionsRow
	for rows.Next() {
		var i GetMemoRecipientsWithActionsRow
		if err := rows.Scan(
			&i.StaffID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.ActionStatus,
			&i.RejectReason,
			&i.AcceptedAt,
			&i.RejectedAt,
			&i.ActionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isMemoRecipient = `-- name: IsMemoRecipient :one
SELECT COUNT(*) AS count
FROM tbl_memo_recipients
WHERE memo_id = ? AND staff_id = ?
`

type IsMemoRecipientParams struct {
	MemoID  int64
	StaffID int64
}

func (q *Queries) IsMemoRecipient(ctx context.Context, arg IsMemoRecipientParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isMemoRecipient, arg.MemoID, arg.StaffID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
