// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: product_inventory.sql

package queries

import (
	"context"
	"database/sql"
)

const adminGetProductInventoriesListing = `-- name: AdminGetProductInventoriesListing :many
SELECT
    tbl_product_inventories.id,
    tbl_product_inventories.stocks,
    tbl_product_inventories.stocks_in,
    tbl_product_inventories.updated_at,
    tbl_products.serial AS product_serial
FROM tbl_product_inventories
INNER JOIN tbl_products ON tbl_products.id = tbl_product_inventories.product_id
ORDER BY
    CASE
        WHEN tbl_product_inventories.stocks = 0 THEN 0
        WHEN tbl_product_inventories.stocks <= 10 THEN 1
        ELSE 2
    END ASC,
    tbl_product_inventories.stocks ASC,
    tbl_product_inventories.updated_at DESC
`

type AdminGetProductInventoriesListingRow struct {
	ID            int64
	Stocks        int64
	StocksIn      string
	UpdatedAt     string
	ProductSerial string
}

func (q *Queries) AdminGetProductInventoriesListing(ctx context.Context) ([]AdminGetProductInventoriesListingRow, error) {
	rows, err := q.db.QueryContext(ctx, adminGetProductInventoriesListing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminGetProductInventoriesListingRow
	for rows.Next() {
		var i AdminGetProductInventoriesListingRow
		if err := rows.Scan(
			&i.ID,
			&i.Stocks,
			&i.StocksIn,
			&i.UpdatedAt,
			&i.ProductSerial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProductInventory = `-- name: CreateProductInventory :one
INSERT INTO tbl_product_inventories (
    product_id,
    stocks,
    stocks_in,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    DATETIME('now'),
    DATETIME('now')
) RETURNING id
`

type CreateProductInventoryParams struct {
	ProductID int64
	Stocks    int64
	StocksIn  string
}

func (q *Queries) CreateProductInventory(ctx context.Context, arg CreateProductInventoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createProductInventory, arg.ProductID, arg.Stocks, arg.StocksIn)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getProductInventoryByID = `-- name: GetProductInventoryByID :one
SELECT
    id,
    product_id,
    stocks,
    stocks_in,
    created_at,
    updated_at
FROM tbl_product_inventories
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetProductInventoryByID(ctx context.Context, id int64) (TblProductInventory, error) {
	row := q.db.QueryRowContext(ctx, getProductInventoryByID, id)
	var i TblProductInventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Stocks,
		&i.StocksIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductInventoryByProductID = `-- name: GetProductInventoryByProductID :one
SELECT
    id,
    product_id,
    stocks,
    stocks_in,
    created_at,
    updated_at
FROM tbl_product_inventories
WHERE product_id = ?
LIMIT 1
`

func (q *Queries) GetProductInventoryByProductID(ctx context.Context, productID int64) (TblProductInventory, error) {
	row := q.db.QueryRowContext(ctx, getProductInventoryByProductID, productID)
	var i TblProductInventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Stocks,
		&i.StocksIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductInventories = `-- name: ListProductInventories :many
SELECT
    tbl_product_inventories.id,
    tbl_product_inventories.product_id,
    tbl_product_inventories.stocks,
    tbl_product_inventories.stocks_in,
    tbl_product_inventories.created_at,
    tbl_product_inventories.updated_at,
    tbl_products.name AS product_name,
    tbl_products.slug AS product_slug
FROM tbl_product_inventories
INNER JOIN tbl_products ON tbl_products.id = tbl_product_inventories.product_id
ORDER BY tbl_products.name ASC
LIMIT ?
`

type ListProductInventoriesRow struct {
	ID          int64
	ProductID   int64
	Stocks      int64
	StocksIn    string
	CreatedAt   string
	UpdatedAt   string
	ProductName string
	ProductSlug sql.NullString
}

func (q *Queries) ListProductInventories(ctx context.Context, limit int64) ([]ListProductInventoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductInventories, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductInventoriesRow
	for rows.Next() {
		var i ListProductInventoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Stocks,
			&i.StocksIn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.ProductSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductInventory = `-- name: UpdateProductInventory :exec
UPDATE tbl_product_inventories
SET
    stocks = ?,
    updated_at = DATETIME('now')
WHERE product_id = ? AND stocks_in = ?
`

type UpdateProductInventoryParams struct {
	Stocks    int64
	ProductID int64
	StocksIn  string
}

func (q *Queries) UpdateProductInventory(ctx context.Context, arg UpdateProductInventoryParams) error {
	_, err := q.db.ExecContext(ctx, updateProductInventory, arg.Stocks, arg.ProductID, arg.StocksIn)
	return err
}
