// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: quotation.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createQuotation = `-- name: CreateQuotation :one
INSERT INTO tbl_quotations(
	customer_id,
	acknowledged_by_staff_id,
	status,
	created_at,
	updated_at
) VALUES (
	?,
	?,
	'DRAFT',
	datetime('now'),
	datetime('now')
) RETURNING id, customer_id, acknowledged_by_staff_id, status, created_at, updated_at
`

type CreateQuotationParams struct {
	CustomerID            int64
	AcknowledgedByStaffID sql.NullInt64
}

func (q *Queries) CreateQuotation(ctx context.Context, arg CreateQuotationParams) (TblQuotation, error) {
	row := q.db.QueryRowContext(ctx, createQuotation, arg.CustomerID, arg.AcknowledgedByStaffID)
	var i TblQuotation
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AcknowledgedByStaffID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuotationLine = `-- name: CreateQuotationLine :one
INSERT INTO tbl_quotation_lines(
	quotation_id,
	product_id,
	quantity,
	original_price_snapshot,
	sale_price_snapshot,
	currency,
	created_at,
	updated_at
) VALUES (
	?,
	?,
	?,
	?,
	?,
	?,
	datetime('now'),
	datetime('now')
) RETURNING id, quotation_id, product_id, quantity, original_price_snapshot, sale_price_snapshot, currency, created_at, updated_at
`

type CreateQuotationLineParams struct {
	QuotationID           int64
	ProductID             int64
	Quantity              int64
	OriginalPriceSnapshot sql.NullInt64
	SalePriceSnapshot     sql.NullInt64
	Currency              string
}

func (q *Queries) CreateQuotationLine(ctx context.Context, arg CreateQuotationLineParams) (TblQuotationLine, error) {
	row := q.db.QueryRowContext(ctx, createQuotationLine,
		arg.QuotationID,
		arg.ProductID,
		arg.Quantity,
		arg.OriginalPriceSnapshot,
		arg.SalePriceSnapshot,
		arg.Currency,
	)
	var i TblQuotationLine
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.ProductID,
		&i.Quantity,
		&i.OriginalPriceSnapshot,
		&i.SalePriceSnapshot,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuotationLine = `-- name: DeleteQuotationLine :exec
DELETE FROM tbl_quotation_lines
WHERE id = ?
`

func (q *Queries) DeleteQuotationLine(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQuotationLine, id)
	return err
}

const getActiveQuotationByCustomerID = `-- name: GetActiveQuotationByCustomerID :one
SELECT id, customer_id, acknowledged_by_staff_id, status, created_at, updated_at FROM tbl_quotations
WHERE customer_id = ? AND status = 'DRAFT'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveQuotationByCustomerID(ctx context.Context, customerID int64) (TblQuotation, error) {
	row := q.db.QueryRowContext(ctx, getActiveQuotationByCustomerID, customerID)
	var i TblQuotation
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AcknowledgedByStaffID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotationLinesByQuotationID = `-- name: GetQuotationLinesByQuotationID :many
SELECT
	tbl_quotation_lines.id, tbl_quotation_lines.quotation_id, tbl_quotation_lines.product_id, tbl_quotation_lines.quantity, tbl_quotation_lines.original_price_snapshot, tbl_quotation_lines.sale_price_snapshot, tbl_quotation_lines.currency, tbl_quotation_lines.created_at, tbl_quotation_lines.updated_at,
	tbl_products.serial AS product_serial,
	tbl_products.name AS product_name,
	tbl_brands.name AS brand_name
FROM tbl_quotation_lines
INNER JOIN tbl_products ON tbl_products.id = tbl_quotation_lines.product_id
INNER JOIN tbl_brands ON tbl_brands.id = tbl_products.brand_id
LEFT JOIN tbl_product_sales ON tbl_product_sales.product_id = tbl_products.id AND tbl_product_sales.is_active = 1
WHERE tbl_quotation_lines.quotation_id = ?
ORDER BY tbl_quotation_lines.created_at DESC
`

type GetQuotationLinesByQuotationIDRow struct {
	ID                    int64
	QuotationID           int64
	ProductID             int64
	Quantity              int64
	OriginalPriceSnapshot sql.NullInt64
	SalePriceSnapshot     sql.NullInt64
	Currency              string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	ProductSerial         string
	ProductName           string
	BrandName             string
}

func (q *Queries) GetQuotationLinesByQuotationID(ctx context.Context, quotationID int64) ([]GetQuotationLinesByQuotationIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuotationLinesByQuotationID, quotationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuotationLinesByQuotationIDRow
	for rows.Next() {
		var i GetQuotationLinesByQuotationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.QuotationID,
			&i.ProductID,
			&i.Quantity,
			&i.OriginalPriceSnapshot,
			&i.SalePriceSnapshot,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductSerial,
			&i.ProductName,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuotationSummary = `-- name: GetQuotationSummary :one
SELECT
	COUNT(*) AS total_items,
	COALESCE(CAST(SUM(tbl_quotation_lines.quantity * tbl_quotation_lines.original_price_snapshot) AS INTEGER), 0) AS total_original_price,
	COALESCE(CAST(SUM(tbl_quotation_lines.quantity * COALESCE(tbl_quotation_lines.sale_price_snapshot, tbl_quotation_lines.original_price_snapshot)) AS INTEGER), 0) AS total_sale_price,
	CAST(COALESCE(currency, '') AS TEXT) AS currency
FROM tbl_quotation_lines
WHERE tbl_quotation_lines.quotation_id = ?
`

type GetQuotationSummaryRow struct {
	TotalItems         int64
	TotalOriginalPrice interface{}
	TotalSalePrice     interface{}
	Currency           string
}

func (q *Queries) GetQuotationSummary(ctx context.Context, quotationID int64) (GetQuotationSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getQuotationSummary, quotationID)
	var i GetQuotationSummaryRow
	err := row.Scan(
		&i.TotalItems,
		&i.TotalOriginalPrice,
		&i.TotalSalePrice,
		&i.Currency,
	)
	return i, err
}

const updateQuotationAcknowledgedBy = `-- name: UpdateQuotationAcknowledgedBy :one
UPDATE tbl_quotations
SET acknowledged_by_staff_id = ?,
	updated_at = datetime('now')
WHERE id = ?
RETURNING id, customer_id, acknowledged_by_staff_id, status, created_at, updated_at
`

type UpdateQuotationAcknowledgedByParams struct {
	AcknowledgedByStaffID sql.NullInt64
	ID                    int64
}

func (q *Queries) UpdateQuotationAcknowledgedBy(ctx context.Context, arg UpdateQuotationAcknowledgedByParams) (TblQuotation, error) {
	row := q.db.QueryRowContext(ctx, updateQuotationAcknowledgedBy, arg.AcknowledgedByStaffID, arg.ID)
	var i TblQuotation
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AcknowledgedByStaffID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuotationLineQuantity = `-- name: UpdateQuotationLineQuantity :one
UPDATE tbl_quotation_lines
SET quantity = ?,
	updated_at = datetime('now')
WHERE id = ?
RETURNING id, quotation_id, product_id, quantity, original_price_snapshot, sale_price_snapshot, currency, created_at, updated_at
`

type UpdateQuotationLineQuantityParams struct {
	Quantity int64
	ID       int64
}

func (q *Queries) UpdateQuotationLineQuantity(ctx context.Context, arg UpdateQuotationLineQuantityParams) (TblQuotationLine, error) {
	row := q.db.QueryRowContext(ctx, updateQuotationLineQuantity, arg.Quantity, arg.ID)
	var i TblQuotationLine
	err := row.Scan(
		&i.ID,
		&i.QuotationID,
		&i.ProductID,
		&i.Quantity,
		&i.OriginalPriceSnapshot,
		&i.SalePriceSnapshot,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuotationStatus = `-- name: UpdateQuotationStatus :one
UPDATE tbl_quotations
SET status = ?,
	updated_at = datetime('now')
WHERE id = ?
RETURNING id, customer_id, acknowledged_by_staff_id, status, created_at, updated_at
`

type UpdateQuotationStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateQuotationStatus(ctx context.Context, arg UpdateQuotationStatusParams) (TblQuotation, error) {
	row := q.db.QueryRowContext(ctx, updateQuotationStatus, arg.Status, arg.ID)
	var i TblQuotation
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AcknowledgedByStaffID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
