version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - usestdlibvars
    - prealloc
    - perfsprint
    - tparallel
    - whitespace
    - fatcontext

issues:
  exclude-use-default: false

exclusions:
  paths:
    - cmd/goose/
    - cmd/thumbnailify_images.go
    - cmd/convert_images.go
