version: "2"
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - usestdlibvars
    - prealloc
    - perfsprint
    - tparallel
    - whitespace
    - fatcontext
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - cmd/goose/
      - cmd/thumbnailify_images.go
      - cmd/convert_images.go
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
