// Code generated by "stringer -type=StorageProvider -trimprefix=STORAGE_PROVIDER_"; DO NOT EDIT.

package storage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STORAGE_PROVIDER_UNDEFINED-0]
	_ = x[STORAGE_PROVIDER_LOCAL-1]
	_ = x[STORAGE_PROVIDER_LINODE-2]
	_ = x[STORAGE_PROVIDER_CLOUDFLARE_IMAGES-3]
}

const _StorageProvider_name = "UNDEFINEDLOCALLINODECLOUDFLARE_IMAGES"

var _StorageProvider_index = [...]uint8{0, 9, 14, 20, 37}

func (i StorageProvider) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StorageProvider_index)-1 {
		return "StorageProvider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageProvider_name[_StorageProvider_index[idx]:_StorageProvider_index[idx+1]]
}
