// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query_user.sql

package cchoice_db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO tbl_user (
	first_name,
	middle_name,
	last_name,
	email,
	password,
	mobile_no,
	user_type,
	status
) VALUES (
	?, ?, ?, ?,
	?, ?, ?, ?
) RETURNING id
`

type CreateUserParams struct {
	FirstName  string
	MiddleName string
	LastName   string
	Email      string
	Password   string
	MobileNo   string
	UserType   string
	Status     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.MobileNo,
		arg.UserType,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByEMailAndUserType = `-- name: GetUserByEMailAndUserType :one
SELECT id
FROM tbl_user
WHERE
	email = ? AND
	user_type = ? AND
	status = 'ACTIVE'
LIMIT 1
`

type GetUserByEMailAndUserTypeParams struct {
	Email    string
	UserType string
}

func (q *Queries) GetUserByEMailAndUserType(ctx context.Context, arg GetUserByEMailAndUserTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserByEMailAndUserType, arg.Email, arg.UserType)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, middle_name, last_name, email, password, mobile_no, user_type, status, created_at, updated_at, deleted_at
FROM tbl_user
WHERE
	id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (TblUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i TblUser
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.MobileNo,
		&i.UserType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserIDAndHashedPassword = `-- name: GetUserIDAndHashedPassword :one
SELECT id, password
FROM tbl_user
WHERE
	user_type = 'API' AND
	status = 'ACTIVE' AND
	email = ?
LIMIT 1
`

type GetUserIDAndHashedPasswordRow struct {
	ID       int64
	Password string
}

func (q *Queries) GetUserIDAndHashedPassword(ctx context.Context, email string) (GetUserIDAndHashedPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, getUserIDAndHashedPassword, email)
	var i GetUserIDAndHashedPasswordRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}
