{
 "title": "Metrics Overview",
 "tags": [
  "cchoice",
  "metrics-overview"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "scrape_job",
    "label": "scrape_job",
    "query": {
     "query": "label_values({__name__=~\".+\", job=~\"integrations/metrics_endpoint/.+\"}, scrape_job)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values({job=~\"integrations/metrics_endpoint/.+\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Random Promo Products",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without (datetime) (\n  cchoice_promo_product_impressions_total\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cchoice_client_client_event", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(cchoice_http_requests_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(cchoice_http_routes_skipped_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(cchoice_http_errors_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}