// Code generated by "stringer -type=AppEnv -trimprefix=APP_ENV_"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APP_ENV_UNDEFINED-0]
	_ = x[APP_ENV_LOCAL-1]
	_ = x[APP_ENV_WEB-2]
	_ = x[APP_ENV_PROD-3]
}

const _AppEnv_name = "UNDEFINEDLOCALWEBPROD"

var _AppEnv_index = [...]uint8{0, 9, 14, 17, 21}

func (i AppEnv) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AppEnv_index)-1 {
		return "AppEnv(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AppEnv_name[_AppEnv_index[idx]:_AppEnv_index[idx+1]]
}
