// Code generated by "stringer -type=AudKind -trimprefix=AUD_"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AUD_UNDEFINED-0]
	_ = x[AUD_API-1]
	_ = x[AUD_SYSTEM-2]
}

const _AudKind_name = "UNDEFINEDAPISYSTEM"

var _AudKind_index = [...]uint8{0, 9, 12, 18}

func (i AudKind) String() string {
	if i < 0 || i >= AudKind(len(_AudKind_index)-1) {
		return "AudKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AudKind_name[_AudKind_index[i]:_AudKind_index[i+1]]
}
