// Code generated by "stringer -type=ExternalPlatform -trimprefix=EXTERNAL_PLATFORM_"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EXTERNAL_PLATFORM_UNDEFINED-0]
	_ = x[EXTERNAL_PLATFORM_LAZADA-1]
	_ = x[EXTERNAL_PLATFORM_TIKTOK-2]
	_ = x[EXTERNAL_PLATFORM_SHOPEE-3]
}

const _ExternalPlatform_name = "UNDEFINEDLAZADATIKTOKSHOPEE"

var _ExternalPlatform_index = [...]uint8{0, 9, 15, 21, 27}

func (i ExternalPlatform) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ExternalPlatform_index)-1 {
		return "ExternalPlatform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExternalPlatform_name[_ExternalPlatform_index[idx]:_ExternalPlatform_index[idx+1]]
}
