// Code generated by "stringer -type=LinodeBucketEnum -trimprefix=LINODE_BUCKET_"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LINODE_BUCKET_UNDEFINED-0]
	_ = x[LINODE_BUCKET_PUBLIC-1]
	_ = x[LINODE_BUCKET_PRIVATE-2]
}

const _LinodeBucketEnum_name = "UNDEFINEDPUBLICPRIVATE"

var _LinodeBucketEnum_index = [...]uint8{0, 9, 15, 22}

func (i LinodeBucketEnum) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LinodeBucketEnum_index)-1 {
		return "LinodeBucketEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LinodeBucketEnum_name[_LinodeBucketEnum_index[idx]:_LinodeBucketEnum_index[idx+1]]
}
