package enums

import "strings"

//go:generate go tool stringer -type=Module -trimprefix=MODULE_

type Module int

const (
	MODULE_UNDEFINED Module = iota
	MODULE_ATTENDANCE_REPORT_CSV
	MODULE_ATTENDANCE_REPORT_XLSX
	MODULE_BRAND
	MODULE_BRANDS
	MODULE_CATEGORY
	MODULE_CPOINTS
	MODULE_HOLIDAYS
	MODULE_PASSWORD_RESET
	MODULE_PRODUCT
	MODULE_PRODUCT_INVENTORIES
	MODULE_PRODUCTS
	MODULE_PROMOS
	MODULE_TIME_OFF
	MODULE_TRACKED_LINKS
)

var AllModules = []Module{
	MODULE_ATTENDANCE_REPORT_CSV,
	MODULE_ATTENDANCE_REPORT_XLSX,
	MODULE_BRANDS,
	MODULE_CPOINTS,
	MODULE_HOLIDAYS,
	MODULE_PASSWORD_RESET,
	MODULE_PRODUCT_INVENTORIES,
	MODULE_PRODUCTS,
	MODULE_PROMOS,
	MODULE_TIME_OFF,
	MODULE_TRACKED_LINKS,
}

func ParseModuleToEnum(e string) Module {
	switch strings.ToUpper(e) {
	case MODULE_ATTENDANCE_REPORT_CSV.String():
		return MODULE_ATTENDANCE_REPORT_CSV
	case MODULE_ATTENDANCE_REPORT_XLSX.String():
		return MODULE_ATTENDANCE_REPORT_XLSX
	case MODULE_BRAND.String():
		return MODULE_BRAND
	case MODULE_BRANDS.String():
		return MODULE_BRANDS
	case MODULE_CATEGORY.String():
		return MODULE_CATEGORY
	case MODULE_CPOINTS.String():
		return MODULE_CPOINTS
	case MODULE_HOLIDAYS.String():
		return MODULE_HOLIDAYS
	case MODULE_PASSWORD_RESET.String():
		return MODULE_PASSWORD_RESET
	case MODULE_PRODUCT.String():
		return MODULE_PRODUCT
	case MODULE_PRODUCT_INVENTORIES.String():
		return MODULE_PRODUCT_INVENTORIES
	case MODULE_PRODUCTS.String():
		return MODULE_PRODUCTS
	case MODULE_PROMOS.String():
		return MODULE_PROMOS
	case MODULE_TIME_OFF.String():
		return MODULE_TIME_OFF
	case MODULE_TRACKED_LINKS.String():
		return MODULE_TRACKED_LINKS
	default:
		return MODULE_UNDEFINED
	}
}

func (m Module) IsValid() bool {
	return m != MODULE_UNDEFINED
}
