// Code generated by "stringer -type=OTPStatus -trimprefix=OTP_STATUS_"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OTP_STATUS_UNDEFINED-0]
	_ = x[OTP_STATUS_INITIAL-1]
	_ = x[OTP_STATUS_ENROLLED-2]
	_ = x[OTP_STATUS_SENT_CODE-3]
	_ = x[OTP_STATUS_VALID-4]
}

const _OTPStatus_name = "UNDEFINEDINITIALENROLLEDSENT_CODEVALID"

var _OTPStatus_index = [...]uint8{0, 9, 16, 24, 33, 38}

func (i OTPStatus) String() string {
	if i < 0 || i >= OTPStatus(len(_OTPStatus_index)-1) {
		return "OTPStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OTPStatus_name[_OTPStatus_index[i]:_OTPStatus_index[i+1]]
}
