package enums

//go:generate go tool stringer -type=PaymentStatus -trimprefix=PAYMENT_STATUS_

type PaymentStatus int

const (
	PAYMENT_STATUS_UNDEFINED PaymentStatus = iota
	PAYMENT_STATUS_PENDING
	PAYMENT_STATUS_PROCESSING
	PAYMENT_STATUS_PAID
	PAYMENT_STATUS_SUCCEEDED
	PAYMENT_STATUS_FAILED
	PAYMENT_STATUS_CANCELLED
	PAYMENT_STATUS_REFUNDED
	PAYMENT_STATUS_AWAITING_PAYMENT_METHOD
)

func ParsePaymentStatusToEnum(e string) PaymentStatus {
	switch e {
	case PAYMENT_STATUS_PENDING.String():
		return PAYMENT_STATUS_PENDING
	case PAYMENT_STATUS_PROCESSING.String():
		return PAYMENT_STATUS_PROCESSING
	case PAYMENT_STATUS_PAID.String():
		return PAYMENT_STATUS_PAID
	case PAYMENT_STATUS_SUCCEEDED.String():
		return PAYMENT_STATUS_SUCCEEDED
	case PAYMENT_STATUS_FAILED.String():
		return PAYMENT_STATUS_FAILED
	case PAYMENT_STATUS_CANCELLED.String():
		return PAYMENT_STATUS_CANCELLED
	case PAYMENT_STATUS_REFUNDED.String():
		return PAYMENT_STATUS_REFUNDED
	case PAYMENT_STATUS_AWAITING_PAYMENT_METHOD.String():
		return PAYMENT_STATUS_AWAITING_PAYMENT_METHOD
	default:
		return PAYMENT_STATUS_UNDEFINED
	}
}
