// Code generated by "stringer -type=ReceiptPaymentForm -trimprefix=RECEIPT_PAYMENT_"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RECEIPT_PAYMENT_UNDEFINED-0]
	_ = x[RECEIPT_PAYMENT_CASH-1]
	_ = x[RECEIPT_PAYMENT_CHECK-2]
}

const _ReceiptPaymentForm_name = "UNDEFINEDCASHCHECK"

var _ReceiptPaymentForm_index = [...]uint8{0, 9, 13, 18}

func (i ReceiptPaymentForm) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ReceiptPaymentForm_index)-1 {
		return "ReceiptPaymentForm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReceiptPaymentForm_name[_ReceiptPaymentForm_index[idx]:_ReceiptPaymentForm_index[idx+1]]
}
