package enums

//go:generate go tool stringer -type=StaffRole -trimprefix=STAFF_ROLE_

type StaffRole int

const (
	STAFF_ROLE_UNDEFINED StaffRole = iota
	STAFF_ROLE_CREATE_PRODUCT
	STAFF_ROLE_CREATE_CPOINTS
	STAFF_ROLE_MANAGE_HOLIDAYS
	STAFF_ROLE_MANAGE_BRANDS
	STAFF_ROLE_MANAGE_PROMOS
	STAFF_ROLE_MANAGE_TRACKED_LINKS
	STAFF_ROLE_MANAGE_PRODUCT_INVENTORIES
	STAFF_ROLE_MANAGE_MEMO
	STAFF_ROLE_EXPORTS
	STAFF_ROLE_EXPORTS_PRODUCTS
	STAFF_ROLE_EDIT_PRODUCTS
	STAFF_ROLE_MANAGE_CATEGORIES
	STAFF_ROLE_MANAGE_ORDERS
	STAFF_ROLE_MANAGE_ORDER_STATUS
	STAFF_ROLE_MANAGE_QUOTATIONS
	STAFF_ROLE_MANAGE_THEMES
)

func ParseStaffRoleToEnum(e string) StaffRole {
	switch e {
	case STAFF_ROLE_CREATE_PRODUCT.String():
		return STAFF_ROLE_CREATE_PRODUCT
	case STAFF_ROLE_CREATE_CPOINTS.String():
		return STAFF_ROLE_CREATE_CPOINTS
	case STAFF_ROLE_MANAGE_HOLIDAYS.String():
		return STAFF_ROLE_MANAGE_HOLIDAYS
	case STAFF_ROLE_MANAGE_BRANDS.String():
		return STAFF_ROLE_MANAGE_BRANDS
	case STAFF_ROLE_MANAGE_PROMOS.String():
		return STAFF_ROLE_MANAGE_PROMOS
	case STAFF_ROLE_MANAGE_TRACKED_LINKS.String():
		return STAFF_ROLE_MANAGE_TRACKED_LINKS
	case STAFF_ROLE_MANAGE_PRODUCT_INVENTORIES.String():
		return STAFF_ROLE_MANAGE_PRODUCT_INVENTORIES
	case STAFF_ROLE_MANAGE_MEMO.String():
		return STAFF_ROLE_MANAGE_MEMO
	case STAFF_ROLE_EXPORTS.String():
		return STAFF_ROLE_EXPORTS
	case STAFF_ROLE_EXPORTS_PRODUCTS.String():
		return STAFF_ROLE_EXPORTS_PRODUCTS
	case STAFF_ROLE_EDIT_PRODUCTS.String():
		return STAFF_ROLE_EDIT_PRODUCTS
	case STAFF_ROLE_MANAGE_CATEGORIES.String():
		return STAFF_ROLE_MANAGE_CATEGORIES
	case STAFF_ROLE_MANAGE_ORDERS.String():
		return STAFF_ROLE_MANAGE_ORDERS
	case STAFF_ROLE_MANAGE_ORDER_STATUS.String():
		return STAFF_ROLE_MANAGE_ORDER_STATUS
	case STAFF_ROLE_MANAGE_QUOTATIONS.String():
		return STAFF_ROLE_MANAGE_QUOTATIONS
	case STAFF_ROLE_MANAGE_THEMES.String():
		return STAFF_ROLE_MANAGE_THEMES
	default:
		return STAFF_ROLE_UNDEFINED
	}
}

func MustParseStaffRoleToEnum(e string) StaffRole {
	switch e {
	case STAFF_ROLE_CREATE_PRODUCT.String():
		return STAFF_ROLE_CREATE_PRODUCT
	case STAFF_ROLE_CREATE_CPOINTS.String():
		return STAFF_ROLE_CREATE_CPOINTS
	case STAFF_ROLE_MANAGE_HOLIDAYS.String():
		return STAFF_ROLE_MANAGE_HOLIDAYS
	case STAFF_ROLE_MANAGE_BRANDS.String():
		return STAFF_ROLE_MANAGE_BRANDS
	case STAFF_ROLE_MANAGE_PROMOS.String():
		return STAFF_ROLE_MANAGE_PROMOS
	case STAFF_ROLE_MANAGE_TRACKED_LINKS.String():
		return STAFF_ROLE_MANAGE_TRACKED_LINKS
	case STAFF_ROLE_MANAGE_PRODUCT_INVENTORIES.String():
		return STAFF_ROLE_MANAGE_PRODUCT_INVENTORIES
	case STAFF_ROLE_MANAGE_MEMO.String():
		return STAFF_ROLE_MANAGE_MEMO
	case STAFF_ROLE_EXPORTS.String():
		return STAFF_ROLE_EXPORTS
	case STAFF_ROLE_EXPORTS_PRODUCTS.String():
		return STAFF_ROLE_EXPORTS_PRODUCTS
	case STAFF_ROLE_EDIT_PRODUCTS.String():
		return STAFF_ROLE_EDIT_PRODUCTS
	case STAFF_ROLE_MANAGE_CATEGORIES.String():
		return STAFF_ROLE_MANAGE_CATEGORIES
	case STAFF_ROLE_MANAGE_ORDERS.String():
		return STAFF_ROLE_MANAGE_ORDERS
	case STAFF_ROLE_MANAGE_ORDER_STATUS.String():
		return STAFF_ROLE_MANAGE_ORDER_STATUS
	case STAFF_ROLE_MANAGE_QUOTATIONS.String():
		return STAFF_ROLE_MANAGE_QUOTATIONS
	case STAFF_ROLE_MANAGE_THEMES.String():
		return STAFF_ROLE_MANAGE_THEMES
	default:
		panic("Invalid StaffRole. Got '" + e + "'")
	}
}

func (r StaffRole) IsValid() bool {
	return r != STAFF_ROLE_UNDEFINED
}

func GetAllStaffRoles() []StaffRole {
	return []StaffRole{
		STAFF_ROLE_CREATE_PRODUCT,
		STAFF_ROLE_EDIT_PRODUCTS,
		STAFF_ROLE_CREATE_CPOINTS,
		STAFF_ROLE_MANAGE_HOLIDAYS,
		STAFF_ROLE_MANAGE_BRANDS,
		STAFF_ROLE_MANAGE_PROMOS,
		STAFF_ROLE_MANAGE_TRACKED_LINKS,
		STAFF_ROLE_MANAGE_PRODUCT_INVENTORIES,
		STAFF_ROLE_MANAGE_MEMO,
		STAFF_ROLE_EXPORTS,
		STAFF_ROLE_EXPORTS_PRODUCTS,
		STAFF_ROLE_MANAGE_CATEGORIES,
		STAFF_ROLE_MANAGE_ORDERS,
		STAFF_ROLE_MANAGE_ORDER_STATUS,
		STAFF_ROLE_MANAGE_QUOTATIONS,
		STAFF_ROLE_MANAGE_THEMES,
	}
}

func RoleExists(role StaffRole) bool {
	return role.IsValid()
}
