// Code generated by "stringer -type=ThemeStatus -trimprefix=THEME_STATUS_"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THEME_STATUS_UNDEFINED-0]
	_ = x[THEME_STATUS_DRAFT-1]
	_ = x[THEME_STATUS_PUBLISHED-2]
	_ = x[THEME_STATUS_DELETED-3]
}

const _ThemeStatus_name = "UNDEFINEDDRAFTPUBLISHEDDELETED"

var _ThemeStatus_index = [...]uint8{0, 9, 14, 23, 30}

func (i ThemeStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ThemeStatus_index)-1 {
		return "ThemeStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ThemeStatus_name[_ThemeStatus_index[idx]:_ThemeStatus_index[idx+1]]
}
