package constants

const (
	ActionApprove       = "approve"
	ActionAccept        = "accept"
	ActionReject        = "reject"
	ActionCancel        = "cancel"
	ActionCreate        = "create"
	ActionDelete        = "delete"
	ActionExport        = "export"
	ActionSend          = "send"
	ActionReset         = "reset"
	ActionTrigger       = "trigger"
	ActionRun           = "run"
	ActionUpdate        = "update"
	ActionUpdateStatus  = "update status"
	ActionTimeIn        = "time in"
	ActionTimeOut       = "time out"
	ActionLunchBreakIn  = "lunch break in"
	ActionLunchBreakOut = "lunch break out"
	ActionLogin         = "login"
	ActionLogout        = "logout"
	ActionGrant         = "grant"
	ActionRevoke        = "revoke"
	ActionDownload      = "download"
)

const (
	ModuleAttendance           = "attendance"
	ModuleAttendanceReportCSV  = "attendance_report_csv"
	ModuleAttendanceReportXLSX = "attendance_report_xlsx"
	ModuleBrands               = "brands"
	ModuleCategories           = "categories"
	ModuleCPoints              = "cpoints"
	ModuleHolidays             = "holidays"
	ModuleInvoices             = "invoices"
	ModuleInvoiceConfig        = "invoice_config"
	ModuleInvoiceRecipients    = "invoice_recipients"
	ModuleDeliveryReceipts     = "delivery_receipts"
	ModuleCollectionReceipts   = "collection_receipts"
	ModuleMemos                = "memos"
	ModuleOrders               = "orders"
	ModuleQuotations           = "quotations"
	ModuleProductInventories   = "product_inventories"
	ModulePasswordReset        = "password_reset"
	ModuleProducts             = "products"
	ModuleProductsExportCSV    = "products_export_csv"
	ModuleProductsExportXLSX   = "products_export_xlsx"
	ModuleProductsBulkImport   = "products_bulk_import"
	ModulePromos               = "promos"
	ModuleStaff                = "staffs"
	ModuleThemes               = "themes"
	ModuleTimeOff              = "time_off"
	ModuleTrackedLinks         = "tracked_links"
)
