package shipping

import (
	"strings"
)

type ServiceType int

const (
	SERVICE_TYPE_UNDEFINED ServiceType = iota
	SERVICE_TYPE_STANDARD
	SERVICE_TYPE_EXPRESS
	// Lalamove specific service types
	SERVICE_TYPE_2000KG_ALUMINUM
	SERVICE_TYPE_2000KG_ALUMINUM_LD
	SERVICE_TYPE_2000KG_FB
	SERVICE_TYPE_2000KG_FB_LD
	SERVICE_TYPE_2000KG_OPENTRUCK
	SERVICE_TYPE_2000KG_OPENTRUCK_LD
	SERVICE_TYPE_600KG_MPV
	SERVICE_TYPE_600KG_MPV_LD
	SERVICE_TYPE_MOTORCYCLE
	SERVICE_TYPE_MPV
	SERVICE_TYPE_MPV_INTERCITY
	SERVICE_TYPE_SEDAN
	SERVICE_TYPE_SEDAN_INTERCITY
	SERVICE_TYPE_TRUCK330
	SERVICE_TYPE_10WHEEL_TRUCK
	SERVICE_TYPE_LD_10WHEEL_TRUCK
	SERVICE_TYPE_TRUCK550
	SERVICE_TYPE_VAN
	SERVICE_TYPE_VAN1000
	SERVICE_TYPE_VAN_INTERCITY
	SERVICE_TYPE_PICKUP_800KG_INTERCITY
)

func (st ServiceType) String() string {
	switch st {
	case SERVICE_TYPE_STANDARD:
		return "STANDARD"
	case SERVICE_TYPE_EXPRESS:
		return "EXPRESS"
	case SERVICE_TYPE_2000KG_ALUMINUM:
		return "2000KG_ALUMINUM"
	case SERVICE_TYPE_2000KG_ALUMINUM_LD:
		return "2000KG_ALUMINUM_LD"
	case SERVICE_TYPE_2000KG_FB:
		return "2000KG_FB"
	case SERVICE_TYPE_2000KG_FB_LD:
		return "2000KG_FB_LD"
	case SERVICE_TYPE_2000KG_OPENTRUCK:
		return "2000KG_OPENTRUCK"
	case SERVICE_TYPE_2000KG_OPENTRUCK_LD:
		return "2000KG_OPENTRUCK_LD"
	case SERVICE_TYPE_600KG_MPV:
		return "600KG_MPV"
	case SERVICE_TYPE_600KG_MPV_LD:
		return "600KG_MPV_LD"
	case SERVICE_TYPE_MOTORCYCLE:
		return "MOTORCYCLE"
	case SERVICE_TYPE_MPV:
		return "MPV"
	case SERVICE_TYPE_MPV_INTERCITY:
		return "MPV_INTERCITY"
	case SERVICE_TYPE_SEDAN:
		return "SEDAN"
	case SERVICE_TYPE_SEDAN_INTERCITY:
		return "SEDAN_INTERCITY"
	case SERVICE_TYPE_TRUCK330:
		return "TRUCK330"
	case SERVICE_TYPE_10WHEEL_TRUCK:
		return "10WHEEL_TRUCK"
	case SERVICE_TYPE_LD_10WHEEL_TRUCK:
		return "LD_10WHEEL_TRUCK"
	case SERVICE_TYPE_TRUCK550:
		return "TRUCK550"
	case SERVICE_TYPE_VAN:
		return "VAN"
	case SERVICE_TYPE_VAN1000:
		return "VAN1000"
	case SERVICE_TYPE_VAN_INTERCITY:
		return "VAN_INTERCITY"
	case SERVICE_TYPE_PICKUP_800KG_INTERCITY:
		return "PICKUP_800KG_INTERCITY"
	default:
		return "UNDEFINED"
	}
}

func ParseServiceTypeToEnum(st string) ServiceType {
	switch strings.ToUpper(st) {
	case "STANDARD":
		return SERVICE_TYPE_STANDARD
	case "EXPRESS":
		return SERVICE_TYPE_EXPRESS
	case "2000KG_ALUMINUM":
		return SERVICE_TYPE_2000KG_ALUMINUM
	case "2000KG_ALUMINUM_LD":
		return SERVICE_TYPE_2000KG_ALUMINUM_LD
	case "2000KG_FB":
		return SERVICE_TYPE_2000KG_FB
	case "2000KG_FB_LD":
		return SERVICE_TYPE_2000KG_FB_LD
	case "2000KG_OPENTRUCK":
		return SERVICE_TYPE_2000KG_OPENTRUCK
	case "2000KG_OPENTRUCK_LD":
		return SERVICE_TYPE_2000KG_OPENTRUCK_LD
	case "600KG_MPV":
		return SERVICE_TYPE_600KG_MPV
	case "600KG_MPV_LD":
		return SERVICE_TYPE_600KG_MPV_LD
	case "MOTORCYCLE":
		return SERVICE_TYPE_MOTORCYCLE
	case "MPV":
		return SERVICE_TYPE_MPV
	case "MPV_INTERCITY":
		return SERVICE_TYPE_MPV_INTERCITY
	case "SEDAN":
		return SERVICE_TYPE_SEDAN
	case "SEDAN_INTERCITY":
		return SERVICE_TYPE_SEDAN_INTERCITY
	case "TRUCK330":
		return SERVICE_TYPE_TRUCK330
	case "10WHEEL_TRUCK":
		return SERVICE_TYPE_10WHEEL_TRUCK
	case "LD_10WHEEL_TRUCK":
		return SERVICE_TYPE_LD_10WHEEL_TRUCK
	case "TRUCK550":
		return SERVICE_TYPE_TRUCK550
	case "VAN":
		return SERVICE_TYPE_VAN
	case "VAN1000":
		return SERVICE_TYPE_VAN1000
	case "VAN_INTERCITY":
		return SERVICE_TYPE_VAN_INTERCITY
	case "PICKUP_800KG_INTERCITY":
		return SERVICE_TYPE_PICKUP_800KG_INTERCITY
	default:
		return SERVICE_TYPE_STANDARD
	}
}

func (st ServiceType) ToLower() string {
	return strings.ToLower(st.String())
}

func (st ServiceType) MarshalJSON() ([]byte, error) {
	return []byte(`"` + st.ToLower() + `"`), nil
}

func (st *ServiceType) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), `"`)
	*st = ParseServiceTypeToEnum(str)
	return nil
}
