name: golangci-lint

on:
  pull_request:
    branches: [main]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.3
        args: --config=${{ github.workspace }}/.golangci.yml
